In [2]:
import numpy as np
numbers = np.arange(1,6)
numbers

array([1, 2, 3, 4, 5])

In [3]:
numbers2 = numbers.view()
numbers2

array([1, 2, 3, 4, 5])

In [4]:
id(numbers)
id(numbers2)

140295791439472

In [6]:
numbers[1] *= 10
numbers

array([ 1, 20, 30,  4,  5])

In [7]:
numbers2[1] /= 10
numbers2

array([ 1,  2, 30,  4,  5])

In [8]:
numbers2 = numbers[0:3]
numbers2

array([ 1,  2, 30])

In [9]:
numbers[1] *= 20
numbers

array([ 1, 40, 30,  4,  5])

In [10]:
numbers2[1] /= 20
numbers2

array([ 1,  2, 30])

In [11]:
numbers = np.arange(1,6)
numbers

array([1, 2, 3, 4, 5])

In [12]:
numbers2 = numbers.copy()
numbers2

array([1, 2, 3, 4, 5])

In [13]:
numbers[1] *= 10
numbers

array([ 1, 20,  3,  4,  5])

In [14]:
grades = np.array([[87,96,70],
                    [100,87,90]])
grades

array([[ 87,  96,  70],
       [100,  87,  90]])

In [15]:
grades.reshape(1,6)

array([[ 87,  96,  70, 100,  87,  90]])

In [17]:
grades

array([[ 87,  96,  70, 100,  87,  90]])

In [16]:
grades.resize(1,6)

In [18]:
grades

array([[ 87,  96,  70, 100,  87,  90]])

In [19]:
flattened = grades.flatten()
flattened

array([ 87,  96,  70, 100,  87,  90])

In [20]:
flattened[0] = 100
flattened

array([100,  96,  70, 100,  87,  90])

In [21]:
raveled = grades.ravel()
raveled

array([ 87,  96,  70, 100,  87,  90])

In [22]:
raveled[0] = 100
raveled

array([100,  96,  70, 100,  87,  90])

In [23]:
grades.T

array([[100],
       [ 96],
       [ 70],
       [100],
       [ 87],
       [ 90]])

In [24]:
grades2 = np.array([[94,77,90],
                    [100,81,82]])
grades2

array([[ 94,  77,  90],
       [100,  81,  82]])

In [26]:
grades = np.array([[87,96,70],
                    [100,87,90]])
grades

array([[ 87,  96,  70],
       [100,  87,  90]])

In [27]:
np.hstack((grades, grades2))

array([[ 87,  96,  70,  94,  77,  90],
       [100,  87,  90, 100,  81,  82]])

In [28]:
np.vstack((grades,grades2))

array([[ 87,  96,  70],
       [100,  87,  90],
       [ 94,  77,  90],
       [100,  81,  82]])