In [9]:
import numpy as np
integers = np.array([[1,2,3],[4,5,6]])
integers

array([[1, 2, 3],
       [4, 5, 6]])

This will create a two-dimensional numpy array

In [8]:
floats = np.array([0.0,0.1,0.2,0.3])
floats

array([0. , 0.1, 0.2, 0.3])

This will create a one-dimensional array

In [6]:
for row in integers: 
    for col in row: 
        print(col, end = ' ')
        print()

1 
2 
3 
4 
5 
6 


In [7]:
for i in integers.flat:
    print(i,end=' ')


1 2 3 4 5 6 

In [11]:
zeros = np.zeros(5)
zeros
ones = np.ones((2,4), dtype=int)
ones 
thirteen = np.full((3,5),13)
thirteen

array([[13, 13, 13, 13, 13],
       [13, 13, 13, 13, 13],
       [13, 13, 13, 13, 13]])

In [13]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [15]:
np.arange(5,10)

array([5, 6, 7, 8, 9])

In [16]:
np.arange(10,5,-2)

array([10,  8,  6])

In [17]:
np.linspace(0.0,1.0,num=5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [19]:
np.arange(1,21).reshape(4,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [23]:
np.arange(1,100001).reshape(100,1000)

array([[     1,      2,      3, ...,    998,    999,   1000],
       [  1001,   1002,   1003, ...,   1998,   1999,   2000],
       [  2001,   2002,   2003, ...,   2998,   2999,   3000],
       ...,
       [ 97001,  97002,  97003, ...,  97998,  97999,  98000],
       [ 98001,  98002,  98003, ...,  98998,  98999,  99000],
       [ 99001,  99002,  99003, ...,  99998,  99999, 100000]])

In [24]:
numbers = np.arange(1,6)
numbers

array([1, 2, 3, 4, 5])

In [25]:
numbers * 2

array([ 2,  4,  6,  8, 10])

In [26]:
numbers ** 3

array([  1,   8,  27,  64, 125])

In [28]:
numbers += 10
numbers

array([21, 22, 23, 24, 25])

In [32]:
numbers2 = np.linspace(1.1,5.5,5)
numbers2
numbers * numbers2

array([ 23.1,  48.4,  75.9, 105.6, 137.5])

In [35]:
numbers = np.aray([11,12,13,14,15])
numbers >= 13

AttributeError: module 'numpy' has no attribute 'aray'

In [36]:
numbers2 

array([1.1, 2.2, 3.3, 4.4, 5.5])

In [37]:
numbers2 < numbers

array([ True,  True,  True,  True,  True])

In [38]:
numbers == numbers2

array([False, False, False, False, False])

In [39]:
numbers == numbers

array([ True,  True,  True,  True,  True])

In [41]:
grades = np.array([[87,96,70],
[100,87,90],
[94,77,90],
[100,81,82]])
grades

array([[ 87,  96,  70],
       [100,  87,  90],
       [ 94,  77,  90],
       [100,  81,  82]])

In [42]:
grades.sum()

1054

In [43]:
grades.min()

70

In [44]:
grades.max()

100

In [45]:
grades.mean()

87.83333333333333

In [46]:
grades.std()

8.792357792739987

In [47]:
grades.var()

77.30555555555556

In [48]:
grades.mean(axis=0)

array([95.25, 85.25, 83.  ])

In [49]:
grades.mean(axis=1)

array([84.33333333, 92.33333333, 87.        , 87.66666667])

In [51]:
numbers = np.array([1,4,9,16,25,36])
np.sqrt(numbers)

array([1., 2., 3., 4., 5., 6.])

In [57]:
numbers2 = np.array([10,20,30,40,50,60])
np.add(numbers,numbers2)

array([11, 24, 39, 56, 75, 96])

In [53]:
np.multiply(numbers2,5)

array([ 50, 100, 150, 200, 250, 300])

In [59]:
numbers3 = numbers2.reshape(2,3)
numbers3

array([[10, 20, 30],
       [40, 50, 60]])

In [61]:
numbers4 = np.array([2,4,6])
np.multiply(numbers3, numbers4)

array([[ 20,  80, 180],
       [ 80, 200, 360]])