In [1]:
import numpy as np

In [3]:
grades = np.array(([87,96,70],
                    [100,87,90],
                    [94,77,90],
                    [100,81,82]))
grades

array([[ 87,  96,  70],
       [100,  87,  90],
       [ 94,  77,  90],
       [100,  81,  82]])

In [4]:
grades[0,1]

96

This is for a single value from a row, col index

In [5]:
grades[1]

array([100,  87,  90])

This is for a single row

In [6]:
grades[:2]

array([[ 87,  96,  70],
       [100,  87,  90]])

This is for sequential rows

In [7]:
grades[[1,2]]

array([[100,  87,  90],
       [ 94,  77,  90]])

This is for non-sequential rows

In [8]:
grades[:,0]

array([ 87, 100,  94, 100])

This is for all rows and first column

In [9]:
grades[:,1:3]

array([[96, 70],
       [87, 90],
       [77, 90],
       [81, 82]])

This is for sequential columns

In [11]:
grades[:,[0,2]]

array([[ 87,  70],
       [100,  90],
       [ 94,  90],
       [100,  82]])